import {readFile,writeFile,mkdir} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const records=JSON.parse(await readFile(new URL('catalog.json',root),'utf8'));
await mkdir(new URL('records/',root),{recursive:true});
for(const r of records){
 const text=`# ${r.title}\n\n${r.status} · ${r.kind} · reviewed ${r.reviewed}\n\n**Affiliation:** ${r.affiliation}\n\n## Decision and method\n\n${r.workload}\n\n${r.method}\n\n**Baseline:** ${r.baseline}\n\n## Finding\n\n${r.finding}\n\n${r.metrics.map(m=>`- ${m}`).join('\n')}\n\n## Limits\n\n${r.limitations}\n\n## Implication for tools (our interpretation)\n\n${r.implication}\n\nEngine patterns: ${r.patterns.map(p=>'`'+p+'`').join(', ')||'Research only'}\n\n## Primary sources\n\n${r.sources.map(s=>`- [${s.label}](${s.url})`).join('\n')}\n\n${r.revision?`Reviewed revision: \`${r.revision}\`.\n`:''}`;
 await writeFile(new URL(`records/${r.id}.md`,root),text);
}
const index=`# System One Bench\n\nUseful decisions, measured honestly. A public evidence catalog for Jev and future\nSystem One models, maintained alongside [System One Engine](https://systemoneengine.com).\n\nFind a real workload, read what was actually measured, and follow the primary source.\nThis is a curated starting set—not an exhaustive survey or a leaderboard of incomparable scores.\nWe disclose our own work, preserve negative results, and distinguish reported findings\nfrom reproductions. We have not independently rerun third-party benchmarks.\n\n## Evidence library\n\n| Scenario | Evidence | Practical finding |\n| --- | --- | --- |\n${records.map(r=>`| [${r.title}](records/${r.id}.md) | ${r.status} · ${r.kind} | ${r.headline} |`).join('\n')}\n\n## What this suggests building\n\n- **Explicit finite choices:** tool and taxonomy recommendations over descriptions that match the current task. Keep permissions and actions in the host.\n- **Independent checks over shared evidence:** batch separate questions; measure disagreement, total latency and host review overhead.\n- **Context selection with a review path:** preserve uncertain evidence and test downstream answer quality. A relevance score alone does not prove token savings.\n- **Deterministic gates and reuse first:** avoid a model call for known facts, repeated inputs, completed cues or easily parsed fields.\n- **Observable fallbacks:** missing confidence, errors and deadlines must remain visible. Never turn a probability into authority.\n\nThese are design inferences. Each [record](records/) maps evidence to Engine patterns\nand explains its limits. The Engine Library exposes editable recipes; not every recipe\nhas been independently benchmarked. [Feature evidence map](FEATURE_MAP.md).\n\n## Reproduce and contribute\n\n\`npm test\` validates the catalog without dependencies or model calls.\n\`npm run build\` generates this index and the records.\n\`npm run check:sources\` reports source-revision drift without changing findings.\n\n[Contribution rules](CONTRIBUTING.md) · [Submit evidence](https://github.com/reachjalil/system-one-bench/issues/new/choose)\n\nOriginal summaries and code are MIT licensed. Linked reports, datasets and model services\nretain their own terms. We link upstream data instead of republishing it.\n`;
await writeFile(new URL('README.md',root),index);
